import sqlite3

print("🧹 Đang dọn dẹp kho cũ...")
conn = sqlite3.connect("database.db")
cursor = conn.cursor()

# Xóa kho cũ đi xây lại từ đầu
cursor.execute("DROP TABLE IF EXISTS products")

print("🏗️ Đang xây lại kho mới bổ sung thuộc tính THƯƠNG HIỆU (brand)...")
cursor.execute(
    """
    CREATE TABLE products (
        id TEXT PRIMARY KEY,
        category TEXT NOT NULL,
        brand TEXT NOT NULL,
        name TEXT NOT NULL,
        price INTEGER NOT NULL,
        icon TEXT NOT NULL 
    )
"""
)

# Nạp nguyên dàn siêu xe 64 món kèm link ảnh nét và Hãng sản xuất chuẩn
products_data = [
    # --- SMARTPHONE ---
    (
        "p1",
        "smartphone",
        "Apple",
        "iPhone 15 Pro Max 256GB",
        29990000,
        "img/p1.jpg",
    ),
    (
        "p2",
        "smartphone",
        "Samsung",
        "Samsung Galaxy S24 Ultra",
        31990000,
        "img/p2.jpg",
    ),
    (
        "p3",
        "smartphone",
        "Xiaomi",
        "Xiaomi 14 Pro 5G",
        22500000,
        "img/p3.jpg",
    ),
    (
        "p4",
        "smartphone",
        "Apple",
        "iPhone 14 Pro Max 128GB",
        25500000,
        "img/p4.jpg",
    ),
    (
        "p5",
        "smartphone",
        "Samsung",
        "Samsung Galaxy Z Fold 5",
        35990000,
        "img/SamSungZF5.jpg",
    ),
    (
        "p6",
        "smartphone",
        "Google",
        "Google Pixel 8 Pro",
        21500000,
        "img/p6.jpg",
    ),
    (
        "p7",
        "smartphone",
        "OPPO",
        "OPPO Find X7 Ultra",
        24990000,
        "img/p7.jpg",
    ),
    (
        "p8",
        "smartphone",
        "Asus",
        "Asus ROG Phone 8 Pro",
        27990000,
        "img/p8.jpg",
    ),
    (
        "p9",
        "smartphone",
        "Vivo",
        "Vivo X100 Pro 5G",
        19990000,
        "img/p9.jpg",
    ),
    (
        "p10",
        "smartphone",
        "Xiaomi",
        "Redmi Note 13 Pro+",
        10490000,
        "img/p10.jpg",
    ),
    # --- NOTEBOOK (LAPTOP) ---
    (
        "p11",
        "notebook",
        "Apple",
        "MacBook Pro 14 inch M3",
        39990000,
        "img/p11.jpg",
    ),
    (
        "p12",
        "notebook",
        "Dell",
        "Dell XPS 15 9530",
        45000000,
        "img/p12.jpg",
    ),
    (
        "p13",
        "notebook",
        "Asus",
        "Asus ROG Strix G16",
        35500000,
        "img/p13.jpg",
    ),
    (
        "p14",
        "notebook",
        "Lenovo",
        "Lenovo ThinkPad X1 Carbon Gen 11",
        42500000,
        "img/p14.jpg",
    ),
    (
        "p15",
        "notebook",
        "Acer",
        "Acer Predator Helios 300",
        32990000,
        "img/p15.jpg",
    ),
    (
        "p16",
        "notebook",
        "HP",
        "HP Spectre x360 14",
        38990000,
        "img/p16.jpg",
    ),
    (
        "p17",
        "notebook",
        "MSI",
        "MSI Raider GE78 HX",
        72000000,
        "img/p17.jpg",
    ),
    (
        "p18",
        "notebook",
        "LG",
        "LG Gram 16 2023",
        28990000,
        "img/Lg_gram.jpg",
    ),
    # --- MOUSE (CHUỘT) ---
    (
        "p19",
        "mouse",
        "Logitech",
        "Chuột Logitech G Pro X Superlight",
        3200000,
        "img/p19.jpg",
    ),
    (
        "p20",
        "mouse",
        "Razer",
        "Chuột Razer DeathAdder V3 Pro",
        3490000,
        "img/p20.jpg",
    ),
    (
        "p21",
        "mouse",
        "Logitech",
        "Chuột Logitech G502 Hero",
        990000,
        "img/ChuotLogitech.png",
    ),
    (
        "p22",
        "mouse",
        "SteelSeries",
        "Chuột SteelSeries Aerox 3 Wireless",
        2100000,
        "img/p22.jpg",
    ),
    (
        "p23",
        "mouse",
        "Zowie",
        "Chuột Zowie EC2-CW Wireless",
        3800000,
        "img/p23.jpg",
    ),
    (
        "p24",
        "mouse",
        "Asus",
        "Chuột Asus ROG Gladius III",
        1890000,
        "img/p24.jpg",
    ),
    (
        "p25",
        "mouse",
        "Glorious",
        "Chuột Glorious Model O Wireless",
        1990000,
        "img/Chuột_Wireless.jpg",
    ),
    (
        "p26",
        "mouse",
        "HyperX",
        "Chuột HyperX Pulsefire Haste",
        1200000,
        "img/p26.jpg",
    ),
    # --- KEYBOARD (BÀN PHÍM) ---
    (
        "p27",
        "keyboard",
        "Akko",
        "Bàn phím cơ Akko 3098B",
        1890000,
        "img/p27.jpg",
    ),
    (
        "p28",
        "keyboard",
        "Keychron",
        "Bàn phím Keychron Q1 Pro",
        4500000,
        "img/p28.jpg",
    ),
    (
        "p29",
        "keyboard",
        "Razer",
        "Bàn phím Razer BlackWidow V4",
        5500000,
        "img/p29.jpg",
    ),
    (
        "p30",
        "keyboard",
        "Logitech",
        "Bàn phím Logitech G915 TKL",
        4200000,
        "img/p30.jpg",
    ),
    (
        "p31",
        "keyboard",
        "Leopold",
        "Bàn phím Leopold FC900R PD",
        3300000,
        "img/p31.jpg",
    ),
    (
        "p32",
        "keyboard",
        "Ducky",
        "Bàn phím Ducky One 3",
        2800000,
        "img/p32.jpg",
    ),
    (
        "p33",
        "keyboard",
        "SteelSeries",
        "Bàn phím SteelSeries Apex Pro TKL",
        4890000,
        "img/p33.jpg",
    ),
    (
        "p34",
        "keyboard",
        "Corsair",
        "Bàn phím Corsair K70 RGB MK.2",
        3500000,
        "img/p34.jpg",
    ),
    # --- MONITOR (MÀN HÌNH) ---
    (
        "p35",
        "monitor",
        "LG",
        "Màn hình LG UltraGear 27GN800",
        6990000,
        "img/p35.jpg",
    ),
    (
        "p36",
        "monitor",
        "Dell",
        "Màn hình Dell UltraSharp 4K U2723QE",
        12500000,
        "img/p36.jpg",
    ),
    (
        "p37",
        "monitor",
        "Asus",
        "Màn hình Asus TUF Gaming VG27AQ",
        7800000,
        "img/p37.jpg",
    ),
    (
        "p38",
        "monitor",
        "Samsung",
        'Màn hình Samsung Odyssey G7 32"',
        15990000,
        "img/p38.jpg",
    ),
    (
        "p39",
        "monitor",
        "BenQ",
        "Màn hình BenQ Zowie XL2546K",
        11200000,
        "img/p39.jpg",
    ),
    (
        "p40",
        "monitor",
        "MSI",
        "Màn hình MSI Optix MAG274QRF",
        8500000,
        "img/p40.jpg",
    ),
    # --- DESKTOP (PC BÀN) ---
    (
        "p41",
        "desktop",
        "Custom",
        "PC Gaming Core i5 13400F / RTX 4060",
        22500000,
        "img/p41.jpg",
    ),
    (
        "p42",
        "desktop",
        "Apple",
        "Apple iMac 24-inch M3",
        36990000,
        "img/p42.jpg",
    ),
    (
        "p43",
        "desktop",
        "HP",
        "HP Omen 45L Gaming Desktop",
        55000000,
        "img/p43.jpg",
    ),
    (
        "p44",
        "desktop",
        "Dell",
        "Dell Alienware Aurora R15",
        85000000,
        "img/p44.jpg",
    ),
    (
        "p45",
        "desktop",
        "Custom",
        "PC Đồ Họa Core i9 / RTX 4090",
        120000000,
        "img/p45.jpg",
    ),
    # --- HEADPHONE (TAI NGHE) ---
    (
        "p46",
        "headphone",
        "Sony",
        "Tai nghe Sony WH-1000XM5",
        6990000,
        "img/p46.jpg",
    ),
    (
        "p47",
        "headphone",
        "Apple",
        "Tai nghe AirPods Pro 2",
        5890000,
        "img/p47.jpg",
    ),
    (
        "p48",
        "headphone",
        "Sennheiser",
        "Tai nghe Sennheiser Momentum 4",
        8500000,
        "img/p48.jpg",
    ),
    (
        "p49",
        "headphone",
        "HyperX",
        "Tai nghe HyperX Cloud III",
        2400000,
        "img/p49.jpg",
    ),
    (
        "p50",
        "headphone",
        "Razer",
        "Tai nghe Razer BlackShark V2",
        4200000,
        "img/p50.jpg",
    ),
    # --- CLOCKS (SMARTWATCH) ---
    (
        "p51",
        "clocks",
        "Apple",
        "Apple Watch Series 9",
        9990000,
        "img/p51.jpg",
    ),
    (
        "p52",
        "clocks",
        "Samsung",
        "Samsung Galaxy Watch 6 Classic",
        8990000,
        "img/p52.jpg",
    ),
    (
        "p53",
        "clocks",
        "Garmin",
        "Garmin Fenix 7 Pro",
        22000000,
        "img/p53.jpg",
    ),
    (
        "p54",
        "clocks",
        "Huawei",
        "Huawei Watch GT 4",
        4990000,
        "img/p54.jpg",
    ),
    (
        "p55",
        "clocks",
        "Apple",
        "Apple Watch Ultra 2",
        21500000,
        "img/p55.jpg",
    ),
    # --- PRINTER (MÁY IN) ---
    (
        "p56",
        "printer",
        "Canon",
        "Máy in Canon LBP2900",
        3200000,
        "img/p56.jpg",
    ),
    (
        "p57",
        "printer",
        "HP",
        "Máy in HP LaserJet Pro",
        4500000,
        "img/p57.jpg",
    ),
    (
        "p58",
        "printer",
        "Epson",
        "Máy in Epson EcoTank L3250",
        5200000,
        "img/p58.jpg",
    ),
    # --- TV (TIVI) ---
    (
        "p59",
        "tv",
        "Samsung",
        "Samsung Crystal UHD 4K 55 inch",
        12490000,
        "img/p59.jpg",
    ),
    (
        "p60",
        "tv",
        "Sony",
        "Sony Bravia LED 4K 65 inch",
        18900000,
        "img/p60.jpg",
    ),
    (
        "p61",
        "tv",
        "LG",
        "LG OLED C3 55 inch",
        32500000,
        "img/p61.jpg",
    ),
    (
        "p62",
        "tv",
        "Xiaomi",
        "Xiaomi TV A2 43 inch",
        5990000,
        "img/p62.jpg",
    ),
    # --- HÀNG MỚI THÊM ---
    (
        "p63",
        "smartphone",
        "Apple",
        "iPhone 16 Pro Max 512GB (Vàng Sa Mạc)",
        34990000,
        "img/p63.jpg",
    ),
    (
        "p64",
        "keyboard",
        "Razer",
        "Bàn phím cơ Razer Huntsman V3 Pro",
        6500000,
        "img/p64.jpg",
    ),
]

print("🚚 Đang bơm 64 sản phẩm vào kho...")
cursor.executemany("INSERT INTO products VALUES (?, ?, ?, ?, ?, ?)", products_data)

conn.commit()
conn.close()
print("✅ THÀNH CÔNG! Đã cập nhật xong CSDL với thuộc tính 'brand' xịn sò!")